name: CI-Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: download-code
        uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v2
        with: 
          go-version: 1.18

      - name: test-code
        run: go test -v
      
      - name: run-code
        run: go run main.go


